[package]
name = "rsnc"
version = "0.1.0"
authors = ["Márcio Jales <marcio.dojcosta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
